# Generated by Django 6.1 on 2026-08-21 11:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='SKU')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tamanho', models.CharField(blank=True, max_length=50, verbose_name='tamanho')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Gramas'), ('L', 'Litros'), ('ML', 'Mililitros'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=3, verbose_name='unidade de medida')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preço de venda')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='estoque mínimo')),
                ('estoque_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='estoque máximo')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='products.categoria', verbose_name='categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='products.marca', verbose_name='marca')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['tenant', 'ativo'], name='products_ca_tenant__6fd920_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='unique_categoria_nome_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['tenant', 'ativo'], name='products_ma_tenant__cad0aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='unique_marca_nome_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tenant', 'nome'], name='products_pr_tenant__bac4df_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tenant', 'ativo'], name='products_pr_tenant__2bf6b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('tenant', 'sku'), name='unique_produto_sku_per_tenant'),
        ),
    ]
