# Generated by Django 6.1 on 2026-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN-13. Códigos gerados pelo sistema usam o prefixo 2 (faixa interna de uso da loja), não são GTIN registrados.', max_length=13, verbose_name='código de barras'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tenant', 'codigo_barras'], name='products_pr_tenant__4d6b2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras', ''), _negated=True), fields=('tenant', 'codigo_barras'), name='unique_produto_codigo_barras_per_tenant'),
        ),
    ]
