# Generated by Django 6.1 on 2026-08-26 18:27

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, help_text='PNG, JPG ou WEBP até 2MB.', upload_to=apps.products.models._caminho_imagem_produto, verbose_name='imagem do produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul (8 dígitos).', max_length=8, verbose_name='NCM'),
        ),
    ]
