# Generated by Django 6.1 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('products', '0003_produto_imagem_produto_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, help_text='Código Especificador da Substituição Tributária (7 dígitos).', max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop',
            field=models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações (4 dígitos).', max_length=4, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno gerado automaticamente pelo sistema.', max_length=20, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(blank=True, choices=[('0', '0 — Nacional'), ('1', '1 — Estrangeira — importação direta'), ('2', '2 — Estrangeira — adquirida no mercado interno'), ('3', '3 — Nacional — conteúdo de importação superior a 40%'), ('4', '4 — Nacional — produção conforme processos básicos'), ('5', '5 — Nacional — conteúdo de importação inferior a 40%'), ('6', '6 — Estrangeira — importação direta sem similar nacional'), ('7', '7 — Estrangeira — mercado interno sem similar nacional'), ('8', '8 — Nacional — conteúdo de importação superior a 70%')], default='0', max_length=1, verbose_name='origem da mercadoria'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tenant', 'codigo'], name='products_pr_tenant__391d48_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('tenant', 'codigo'), name='unique_produto_codigo_per_tenant'),
        ),
    ]
