# Generated by Django 5.2.17 on 2026-09-04 00:48

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produto_cest_produto_cfop_produto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, help_text='PNG, JPG ou WEBP até 5MB.', upload_to=apps.products.models._caminho_imagem_produto, verbose_name='imagem do produto'),
        ),
    ]
