# Generated by Django 6.1 on 2026-08-21 21:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('financial', '0001_initial'),
        ('products', '0002_produto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_final_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observacao_fechamento', models.TextField(blank=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('conta_financeira', models.ForeignKey(help_text='Conta onde entradas, suprimentos e sangrias são lançados.', on_delete=django.db.models.deletion.PROTECT, related_name='caixas_pdv', to='financial.contafinanceira')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_operados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='sales.caixa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='companies.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa_pdv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação de caixa',
                'verbose_name_plural': 'movimentações de caixa',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('cliente_nome', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='sales.caixa')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'venda',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='financial.formapagamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='companies.tenant')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='sales.venda')),
            ],
            options={
                'verbose_name': 'pagamento de venda',
                'verbose_name_plural': 'pagamentos de venda',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='products.produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='companies.tenant')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.venda')),
            ],
            options={
                'verbose_name': 'item de venda',
                'verbose_name_plural': 'itens de venda',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['tenant', 'status'], name='sales_caixa_tenant__ab6c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['tenant', 'status'], name='sales_venda_tenant__74dfb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero'), name='unique_venda_numero_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(fields=('venda', 'produto'), name='unique_item_produto_por_venda'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_venda_quantidade_positiva'),
        ),
    ]
