# Generated by Django 6.1 on 2026-08-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente cadastrado associado à venda (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='customers.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente_nome',
            field=models.CharField(blank=True, help_text='Nome do cliente congelado no momento da venda.', max_length=200),
        ),
    ]
