# Generated by Django 6.1 on 2026-08-26 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tenant', 'ativo'], name='customers_c_tenant__8b44ff_idx'), models.Index(fields=['tenant', 'nome'], name='customers_c_tenant__3ccfba_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf_cnpj', ''), _negated=True), fields=('tenant', 'cpf_cnpj'), name='unique_cliente_cpf_cnpj_per_tenant')],
            },
        ),
    ]
