# Generated by Django 6.1 on 2026-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='permitir_estoque_negativo',
            field=models.BooleanField(default=False, help_text='Quando desabilitado, saídas que deixarem o saldo negativo são rejeitadas com erro de domínio.', verbose_name='permitir estoque negativo'),
        ),
    ]
