# Generated by Django 6.1 on 2026-08-23 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10, verbose_name='status')),
                ('token_hash', models.CharField(blank=True, max_length=255, verbose_name='token (hash)')),
                ('codigo_pareamento', models.CharField(blank=True, default='', help_text='Uso único: consumido no primeiro pareamento bem-sucedido.', max_length=6, verbose_name='código de pareamento')),
                ('ultima_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_pareamento', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacoes_impressao', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'estação de impressão',
                'verbose_name_plural': 'estações de impressão',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('largura', models.CharField(choices=[('58', '58 mm (papel 32 colunas)'), ('80', '80 mm (papel 48 colunas)')], default='58', max_length=2, verbose_name='largura do papel')),
                ('impressao_automatica', models.BooleanField(default=True, help_text='Quando ativa, um PrintJob é enfileirado automaticamente ao finalizar cada venda.', verbose_name='impressão automática')),
                ('tentativas_maximas', models.PositiveIntegerField(default=5, help_text='Após esgotar as tentativas o PrintJob vira FAILED.', verbose_name='tentativas máximas')),
                ('nome_loja', models.CharField(blank=True, max_length=255, verbose_name='nome da loja')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('mensagem_final', models.CharField(blank=True, default='Obrigado pela preferência!', max_length=120, verbose_name='mensagem final')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_impressao', to='companies.tenant')),
                ('estacao_padrao', models.ForeignKey(blank=True, help_text='Estação preferencial para os novos PrintJobs. Vazio permite que qualquer estação ativa do tenant assuma o trabalho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='printing.estacaoimpressao', verbose_name='estação padrão')),
            ],
            options={
                'verbose_name': 'configuração de impressão',
                'verbose_name_plural': 'configurações de impressão',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RETRYING', 'Aguardando retry'), ('PROCESSING', 'Imprimindo'), ('PRINTED', 'Impresso'), ('FAILED', 'Falhou')], default='PENDING', max_length=12, verbose_name='status')),
                ('payload', models.JSONField(default=dict, help_text='Snapshot serializável da venda para o comprovante.', verbose_name='payload')),
                ('tentativa', models.PositiveIntegerField(default=0, verbose_name='tentativa')),
                ('tentativas_maximas', models.PositiveIntegerField(default=5, verbose_name='tentativas máximas')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('data_impressao', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('estacao', models.ForeignKey(blank=True, help_text='Estação que assumiu (ou assumirá) o trabalho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='printing.estacaoimpressao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='companies.tenant')),
                ('venda', models.ForeignKey(blank=True, help_text='Venda de origem (snapshot fica no payload).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='sales.venda')),
            ],
            options={
                'verbose_name': 'trabalho de impressão',
                'verbose_name_plural': 'trabalhos de impressão',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='estacaoimpressao',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='unique_estacao_nome_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant', 'status'], name='printing_pr_tenant__7f0180_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant', 'venda'], name='printing_pr_tenant__c3878f_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['estacao'], name='printing_pr_estacao_5f77a0_idx'),
        ),
    ]
