# Generated by Django 6.1 on 2026-08-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoimpressao',
            name='impressao_automatica',
        ),
    ]
