# Generated by Django 5.2.17 on 2026-09-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_remove_configuracaoimpressao_impressao_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='impressora_fiscal',
            field=models.CharField(blank=True, help_text='Nome da impressora de comprovantes (fiscais e não fiscais) instalada na máquina da loja. Enviado ao agente local, que encaminha o trabalho para esse equipamento. Vazio usa a impressora configurada no próprio agente.', max_length=120, verbose_name='impressora fiscal/não fiscal'),
        ),
    ]
