# Generated by Django 6.1 on 2026-08-26 09:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('printing', '0002_remove_configuracaoimpressao_impressao_automatica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_impressora', models.CharField(default='Elgin L42 Pro Full', max_length=80, verbose_name='impressora')),
                ('dpi', models.PositiveIntegerField(default=203, verbose_name='DPI')),
                ('largura_etiqueta', models.DecimalField(decimal_places=1, default=Decimal('40'), max_digits=6, verbose_name='largura da etiqueta (mm)')),
                ('altura_etiqueta', models.DecimalField(decimal_places=1, default=Decimal('30'), max_digits=6, verbose_name='altura da etiqueta (mm)')),
                ('gap_horizontal', models.DecimalField(decimal_places=1, default=Decimal('2'), max_digits=6, verbose_name='espaço horizontal entre etiquetas (mm)')),
                ('gap_vertical', models.DecimalField(decimal_places=1, default=Decimal('2'), max_digits=6, verbose_name='espaço vertical entre fileiras (mm)')),
                ('margem_esquerda', models.DecimalField(decimal_places=1, default=Decimal('2'), max_digits=6, verbose_name='margem esquerda (mm)')),
                ('margem_superior', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=6, verbose_name='margem superior (mm)')),
                ('offset_horizontal', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6, verbose_name='offset horizontal (mm)')),
                ('offset_vertical', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6, verbose_name='offset vertical (mm)')),
                ('mostrar_texto_codigo', models.BooleanField(default=True, verbose_name='exibir o valor abaixo do código de barras')),
                ('quantidade_padrao', models.PositiveIntegerField(default=1, verbose_name='quantidade padrão de etiquetas')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_etiqueta', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'configuração de etiqueta',
                'verbose_name_plural': 'configurações de etiqueta',
            },
        ),
        migrations.CreateModel(
            name='EtiquetaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RETRYING', 'Aguardando retry'), ('PROCESSING', 'Imprimindo'), ('PRINTED', 'Impresso'), ('FAILED', 'Falhou')], default='PENDING', max_length=12, verbose_name='status')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('tentativa', models.PositiveIntegerField(default=0, verbose_name='tentativa')),
                ('tentativas_maximas', models.PositiveIntegerField(default=5, verbose_name='tentativas máximas')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('data_impressao', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('estacao', models.ForeignKey(blank=True, help_text='Estação que assumiu o trabalho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiqueta_jobs', to='printing.estacaoimpressao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiqueta_jobs', to='companies.tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiqueta_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trabalho de etiquetas',
                'verbose_name_plural': 'trabalhos de etiquetas',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='labels_etiq_tenant__e45e7c_idx')],
            },
        ),
    ]
