# Generated by Django 6.1 on 2026-08-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='fiscal/certificados/%Y/%m/')),
                ('validade', models.DateField(verbose_name='validade')),
                ('ativo', models.BooleanField(default=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_digitais', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'certificado digital',
                'verbose_name_plural': 'certificados digitais',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=15, verbose_name='ambiente')),
                ('serie', models.PositiveIntegerField(default=1, verbose_name='série NFC-e')),
                ('proximo_numero', models.PositiveIntegerField(default=1, verbose_name='próximo número')),
                ('token_csc', models.CharField(blank=True, max_length=64, verbose_name='token CSC')),
                ('id_csc', models.CharField(blank=True, max_length=6, verbose_name='identificador CSC')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_fiscal', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'configuração fiscal',
                'verbose_name_plural': 'configurações fiscais',
            },
        ),
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=120, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=120, verbose_name='nome fantasia')),
                ('ie', models.CharField(max_length=20, verbose_name='inscrição estadual')),
                ('crt', models.CharField(choices=[('1', 'Simples Nacional (CSOSN)'), ('2', 'Simples Nacional — excesso de sublimite'), ('3', 'Regime normal (CST)')], default='1', max_length=1, verbose_name='CRT')),
                ('x_lgr', models.CharField(max_length=60, verbose_name='logradouro')),
                ('nro', models.CharField(max_length=60, verbose_name='número')),
                ('x_cpl', models.CharField(blank=True, max_length=60, verbose_name='complemento')),
                ('x_bairro', models.CharField(max_length=60, verbose_name='bairro')),
                ('codigo_municipio_ibge', models.CharField(max_length=7, verbose_name='código IBGE do município')),
                ('x_municipio', models.CharField(max_length=60, verbose_name='município')),
                ('uf', models.CharField(default='SP', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('fone', models.CharField(blank=True, max_length=12, verbose_name='telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emitente', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'emitente',
                'verbose_name_plural': 'emitentes',
            },
        ),
        migrations.CreateModel(
            name='NFCe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.PositiveIntegerField(default=1)),
                ('chave_acesso', models.CharField(db_index=True, max_length=44, unique=True)),
                ('dv', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GERADA', 'XML gerado'), ('ASSINADA', 'Assinada'), ('TRANSMITINDO', 'Transmitindo'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada'), ('CONTINGENCIA_INATIVO', 'Contingência inativa')], default='PENDENTE', max_length=25)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('xml_enviado', models.TextField(blank=True)),
                ('xml_assinado', models.TextField(blank=True)),
                ('xml_autorizado', models.TextField(blank=True)),
                ('codigo_rejeicao', models.CharField(blank=True, max_length=4)),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255)),
                ('url_qrcode', models.URLField(blank=True, max_length=600, verbose_name='URL do QR Code')),
                ('tentativas_consulta', models.PositiveIntegerField(default=0)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfces', to='companies.tenant')),
                ('venda', models.ForeignKey(blank=True, help_text='Emissão avulsa futura pode não ter venda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfces', to='sales.venda')),
            ],
            options={
                'verbose_name': 'NFC-e',
                'verbose_name_plural': 'NFC-es',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('INUTILIZACAO', 'Inutilização')], max_length=15)),
                ('sequencia', models.PositiveSmallIntegerField(default=1)),
                ('justificativa', models.CharField(max_length=255)),
                ('xml_evento', models.TextField(blank=True)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('HOMOLOGADO', 'Homologado'), ('REJEITADO', 'Rejeitado')], default='ENVIADO', max_length=10)),
                ('codigo_rejeicao', models.CharField(blank=True, max_length=4)),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_fiscais', to='companies.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_fiscais', to=settings.AUTH_USER_MODEL)),
                ('nfce', models.ForeignKey(blank=True, help_text='Inutilização não referencia uma NFC-e específica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='fiscal.nfce')),
            ],
            options={
                'verbose_name': 'evento fiscal',
                'verbose_name_plural': 'eventos fiscais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='nfce',
            index=models.Index(fields=['tenant', 'status'], name='nfce_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfce',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDENTE', 'GERADA', 'ASSINADA', 'TRANSMITINDO'])), fields=('venda',), name='unique_nfce_ativa_por_venda'),
        ),
    ]
