# Generated by Django 6.1 on 2026-08-21 12:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('products', '0002_produto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolução'), ('CANCELAMENTO_VENDA', 'Cancelamento de venda'), ('INVENTARIO', 'Inventário')], db_index=True, max_length=20, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Sempre positiva; o sentido vem do tipo.', max_digits=12, verbose_name='quantidade')),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='saldo anterior')),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='saldo posterior')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='custo unitário')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='referência')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.fornecedor', verbose_name='fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='products.produto', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='companies.tenant', verbose_name='tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='quantidade')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='products.produto', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='companies.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoques',
                'indexes': [models.Index(fields=['tenant', 'quantidade'], name='inventory_e_tenant__e96868_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['tenant', 'ativo'], name='inventory_f_tenant__422144_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tenant', 'produto', '-data_criacao'], name='inventory_m_tenant__1c2a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tenant', '-data_criacao'], name='inventory_m_tenant__f1b927_idx'),
        ),
    ]
