# Generated by Django 6.1 on 2026-08-21 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        ('inventory', '0001_initial'),
        ('products', '0002_produto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_CONTAGEM', 'Em contagem'), ('EM_REVISAO', 'Em revisão'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=15, verbose_name='status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='início')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='finalização')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='companies.tenant', verbose_name='tenant')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('usuario_finalizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_finalizados', to=settings.AUTH_USER_MODEL, verbose_name='finalizado por')),
            ],
            options={
                'verbose_name': 'inventário',
                'verbose_name_plural': 'inventários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, help_text='Saldo congelado no momento da criação do item.', max_digits=12, verbose_name='quantidade no sistema')),
                ('quantidade_contada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade contada')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.inventario', verbose_name='inventário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='products.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item de inventário',
                'verbose_name_plural': 'itens de inventário',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['tenant', 'status'], name='inventory_i_tenant__d12028_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventarioitem',
            constraint=models.UniqueConstraint(fields=('inventario', 'produto'), name='unique_item_produto_per_inventario'),
        ),
    ]
