# Generated by Django 6.1 on 2026-08-21 20:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_tenant_permitir_estoque_negativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AMBOS', 'Ambos')], max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='financial.categoriafinanceira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('CAIXA', 'Caixa'), ('CONTA_BANCARIA', 'Conta bancária'), ('CARTEIRA', 'Carteira'), ('PIX', 'PIX'), ('OUTRO', 'Outro')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('permitir_saldo_negativo', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'conta financeira',
                'verbose_name_plural': 'contas financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField()),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('VENDA', 'Venda'), ('OUTRO', 'Outro')], default='MANUAL', max_length=10)),
                ('referencia_uuid', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Parcialmente recebida'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'conta a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['-data_competencia'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], max_length=20)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preparado para taxas de cartão (bruto/taxa/líquido).', max_digits=5)),
                ('gera_conta_receber', models.BooleanField(default=False, help_text='Fiado/crediário: gera conta a receber em vez de entrada imediata.')),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField()),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='financial.categoriafinanceira')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='financial.contafinanceira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='companies.tenant')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_criadas', to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='financial.formapagamento')),
            ],
            options={
                'verbose_name': 'entrada',
                'ordering': ['-data_competencia', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('ESTORNO_ENTRADA', 'Estorno de entrada'), ('ESTORNO_SAIDA', 'Estorno de saída')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('origem', models.CharField(choices=[('ENTRADA', 'Entrada avulsa'), ('SAIDA', 'Saída avulsa'), ('PARCELA', 'Parcela a receber'), ('VENDA', 'Venda do PDV'), ('SUPRIMENTO', 'Suprimento de caixa'), ('SANGRIA', 'Sangria de caixa'), ('ABERTURA_CAIXA', 'Abertura de caixa'), ('MANUAL', 'Manual')], max_length=20)),
                ('referencia_uuid', models.UUIDField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financial.contafinanceira')),
                ('estorno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financial.movimentacaofinanceira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_financeiras', to='companies.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação financeira',
                'verbose_name_plural': 'movimentações financeiras',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('conta_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_recebidas', to='financial.contafinanceira')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financial.contareceber')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_receber', to='companies.tenant')),
            ],
            options={
                'verbose_name': 'parcela a receber',
                'verbose_name_plural': 'parcelas a receber',
                'ordering': ['conta_receber', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='financial.categoriafinanceira')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='financial.contafinanceira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='companies.tenant')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saída',
                'ordering': ['-data_vencimento', '-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['tenant', 'tipo'], name='financial_c_tenant__1b846d_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria_pai__isnull', True)), fields=('tenant', 'nome'), name='unique_categoria_raiz_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='unique_conta_financeira_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['tenant', 'status'], name='financial_c_tenant__5543d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(fields=('tenant', 'codigo'), name='unique_forma_pagamento_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['tenant', 'status'], name='financial_e_tenant__d73d13_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['tenant', 'data_competencia'], name='financial_e_tenant__e905ef_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['tenant', 'data'], name='financial_m_tenant__773d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['conta_financeira', 'data'], name='financial_m_conta_f_0345bd_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelareceber',
            index=models.Index(fields=['tenant', 'status'], name='financial_p_tenant__f2e7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelareceber',
            index=models.Index(fields=['tenant', 'data_vencimento'], name='financial_p_tenant__612a12_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelareceber',
            constraint=models.UniqueConstraint(fields=('conta_receber', 'numero'), name='unique_parcela_numero_por_conta'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['tenant', 'status'], name='financial_s_tenant__f5c7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['tenant', 'data_vencimento'], name='financial_s_tenant__e947f5_idx'),
        ),
    ]
