# Generated by Django 6.1 on 2026-08-21 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PJ', max_length=2, verbose_name='tipo de pessoa')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Armazenado apenas com dígitos. Opcional durante o onboarding (ex.: conversão de lead); obrigatório para ativação.', max_length=14, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone_celular', models.CharField(max_length=20, verbose_name='telefone celular')),
                ('origem', models.CharField(choices=[('SITE', 'Site'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('INDICACAO', 'Indicação'), ('PRESENCIAL', 'Presencial'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='origem')),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('EM_ANALISE', 'Em análise'), ('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], db_index=True, default='LEAD', max_length=20, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='estado (UF)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'cliente da plataforma',
                'verbose_name_plural': 'clientes da plataforma',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ClienteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('ATUALIZADO', 'Atualizado'), ('STATUS_ALTERADO', 'Status alterado'), ('TENANT_ASSOCIADO', 'Tenant associado'), ('ONBOARDING_INICIADO', 'Onboarding iniciado')], max_length=40, verbose_name='ação')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, max_length=20, verbose_name='status novo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_clientes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clients.clienteplataforma', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'histórico do cliente',
                'verbose_name_plural': 'históricos do cliente',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LeadContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('empresa', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20, verbose_name='status')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cliente_convertido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origem', to='clients.clienteplataforma', verbose_name='cliente convertido')),
            ],
            options={
                'verbose_name': 'lead de contato',
                'verbose_name_plural': 'leads de contato',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('DADOS_PENDENTES', 'Dados pendentes'), ('CONFIGURANDO', 'Configurando'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=20, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='iniciado em')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='clients.clienteplataforma', verbose_name='cliente')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='companies.tenant', verbose_name='tenant')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'onboarding',
                'verbose_name_plural': 'onboardings',
            },
        ),
        migrations.AddIndex(
            model_name='clienteplataforma',
            index=models.Index(fields=['status', 'data_cadastro'], name='clients_cli_status_8d62e2_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteplataforma',
            index=models.Index(fields=['email'], name='clients_cli_email_b86844_idx'),
        ),
    ]
