# Generated by Django 6.1 on 2026-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteplataforma',
            name='senha',
            field=models.CharField(blank=True, max_length=128, verbose_name='senha'),
        ),
    ]
