# Generated by Django 6.1 on 2026-08-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clienteplataforma_senha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteplataforma',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Conta de usuário vinculada para login do cliente. Criada automaticamente no primeiro acesso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_plataforma', to=settings.AUTH_USER_MODEL, verbose_name='conta de acesso'),
        ),
    ]
